ALTER TABLE "CombatTuning"
ADD COLUMN IF NOT EXISTS "weaponSkillBraveryWeight" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS "weaponSkillAttackWeight" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "armorSkillFortitudeWeight" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS "armorSkillDefenceWeight" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "willpowerSupportWeight" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS "willpowerBraveryWeight" DOUBLE PRECISION NOT NULL DEFAULT 1;
