ALTER TABLE "ItemTemplate"
ALTER COLUMN "PhysicalStrength" TYPE DOUBLE PRECISION USING "PhysicalStrength"::DOUBLE PRECISION,
ALTER COLUMN "MentalStrength" TYPE DOUBLE PRECISION USING "MentalStrength"::DOUBLE PRECISION,
ALTER COLUMN "meleePhysicalStrength" TYPE DOUBLE PRECISION USING "meleePhysicalStrength"::DOUBLE PRECISION,
ALTER COLUMN "meleeMentalStrength" TYPE DOUBLE PRECISION USING "meleeMentalStrength"::DOUBLE PRECISION,
ALTER COLUMN "rangedPhysicalStrength" TYPE DOUBLE PRECISION USING "rangedPhysicalStrength"::DOUBLE PRECISION,
ALTER COLUMN "rangedMentalStrength" TYPE DOUBLE PRECISION USING "rangedMentalStrength"::DOUBLE PRECISION,
ALTER COLUMN "aoePhysicalStrength" TYPE DOUBLE PRECISION USING "aoePhysicalStrength"::DOUBLE PRECISION,
ALTER COLUMN "aoeMentalStrength" TYPE DOUBLE PRECISION USING "aoeMentalStrength"::DOUBLE PRECISION;
