import { COMBAT_TUNING_CONFIG_KEY_ORDER } from "@/lib/config/combatTuningShared";

export const COMBAT_TUNING_ADMIN_GROUPS = [
  "Protection Formula",
  "Baseline Resilience & Perseverance",
  "Pool Expectation by Tier",
  "Pool Penalty / Bonus Scaling",
  "Attribute Weights / Realization Inputs",
  "Natural Attack Formula",
  "Dodge & Defence Package",
  "Misc Combat Baseline",
] as const;

export type CombatTuningAdminGroup = (typeof COMBAT_TUNING_ADMIN_GROUPS)[number];
export type CombatTuningValueFormat = "number" | "multiplier" | "share";

export type CombatTuningAdminMetadata = {
  label: string;
  group: CombatTuningAdminGroup;
  description: string;
  affects: "baseline";
  format?: CombatTuningValueFormat;
  suggestedMin?: number;
  suggestedMax?: number;
  aliases?: string[];
};

const METADATA: Record<string, CombatTuningAdminMetadata> = {
  protectionK: {
    label: "Protection Output Divider",
    group: "Protection Formula",
    description: "Raise this to make protection block fewer wounds per success.",
    affects: "baseline",
    suggestedMin: 1,
    suggestedMax: 12,
    aliases: ["K", "block", "protection"],
  },
  protectionS: {
    label: "Protection Skill Scaling Divider",
    group: "Protection Formula",
    description: "Raise this to make Armor Skill and Willpower add less block value.",
    affects: "baseline",
    suggestedMin: 1,
    suggestedMax: 12,
    aliases: ["S", "skill", "block", "protection"],
  },
  attackWeight: {
    label: "Attack Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Attack add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  defenceWeight: {
    label: "Defence Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Defence add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  fortitudeWeight: {
    label: "Fortitude Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Fortitude add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  intellectWeight: {
    label: "Intellect Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Intellect add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  supportWeight: {
    label: "Support Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Support add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  braveryWeight: {
    label: "Bravery Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Bravery add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  weaponSkillBraveryWeight: {
    label: "Bravery Weight for Weapon Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Bravery matter more for Weapon Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill"],
  },
  weaponSkillAttackWeight: {
    label: "Attack Weight for Weapon Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Attack matter more for Weapon Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill"],
  },
  weaponSkillBaselineOffset: {
    label: "Weapon Skill Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Weapon Skill overall.",
    affects: "baseline",
    aliases: ["weapon skill", "attack skill", "offset"],
  },
  weaponSkillScale: {
    label: "Weapon Skill Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Weapon Skill faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill", "curve"],
  },
  armorSkillFortitudeWeight: {
    label: "Fortitude Weight for Armor Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Fortitude matter more for Armor Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill"],
  },
  armorSkillDefenceWeight: {
    label: "Defence Weight for Armor Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Defence matter more for Armor Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill"],
  },
  armorSkillBaselineOffset: {
    label: "Armor Skill Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Armor Skill overall.",
    affects: "baseline",
    aliases: ["armor skill", "defence skill", "offset"],
  },
  armorSkillScale: {
    label: "Armor Skill Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Armor Skill faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill", "curve"],
  },
  willpowerSupportWeight: {
    label: "Support Weight for Willpower",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Support matter more for Willpower.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental defence"],
  },
  willpowerBraveryWeight: {
    label: "Bravery Weight for Willpower",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Bravery matter more for Willpower.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental defence"],
  },
  willpowerBaselineOffset: {
    label: "Willpower Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Willpower overall.",
    affects: "baseline",
    aliases: ["willpower", "mental defence", "offset"],
  },
  willpowerScale: {
    label: "Willpower Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Willpower faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental defence", "curve"],
  },
  dodgeIntellectWeight: {
    label: "Intellect Weight for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Intellect increase Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "attribute"],
  },
  dodgeDefenceWeight: {
    label: "Defence Weight for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Defence increase Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "attribute"],
  },
  dodgeAttributeDivisor: {
    label: "Dodge Attribute Divisor",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower the attribute part of Dodge overall.",
    affects: "baseline",
    aliases: ["dodge", "avoidance", "divider", "divisor"],
  },
  dodgeProtectionPenaltyWeight: {
    label: "Protection Penalty for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Physical Protection reduce Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "protection", "penalty"],
  },
  naturalAttackStrengthWoundMultiplier: {
    label: "Natural Attack Wounds per Strength",
    group: "Natural Attack Formula",
    description: "Raise this to make each point of natural attack Strength deal more wounds.",
    affects: "baseline",
    format: "multiplier",
    suggestedMin: 1,
    suggestedMax: 6,
    aliases: ["natural attack", "strength", "wounds", "damage", "natural weapon"],
  },
  naturalAttackLevelWoundBonusDivisor: {
    label: "Natural Attack Level Bonus Divider",
    group: "Natural Attack Formula",
    description: "Raise this to make the extra level-based wound bonus arrive more slowly.",
    affects: "baseline",
    suggestedMin: 1,
    suggestedMax: 10,
    aliases: ["natural attack", "level bonus", "wounds", "damage", "natural weapon"],
  },
  minionTierMultiplier: {
    label: "MINION Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give MINION monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  soldierTierMultiplier: {
    label: "SOLDIER Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give SOLDIER monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  eliteTierMultiplier: {
    label: "ELITE Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give ELITE monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  bossTierMultiplier: {
    label: "BOSS Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give BOSS monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  expectedPhysicalResilienceAt1: {
    label: "Expected Physical Resilience at Level 1",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the calculator expect a tougher physical pool at level 1.",
    affects: "baseline",
    aliases: ["health pool", "physical resilience", "expected"],
  },
  expectedPhysicalResiliencePerLevel: {
    label: "Expected Physical Resilience per Level",
    group: "Pool Expectation by Tier",
    description: "Raise this to make expected physical resilience grow faster by level.",
    affects: "baseline",
    aliases: ["health pool", "physical resilience", "expected"],
  },
  expectedMentalPerseveranceAt1: {
    label: "Expected Mental Perseverance at Level 1",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the calculator expect a tougher mental pool at level 1.",
    affects: "baseline",
    aliases: ["health pool", "mental perseverance", "expected"],
  },
  expectedMentalPerseverancePerLevel: {
    label: "Expected Mental Perseverance per Level",
    group: "Pool Expectation by Tier",
    description: "Raise this to make expected mental perseverance grow faster by level.",
    affects: "baseline",
    aliases: ["health pool", "mental perseverance", "expected"],
  },
  expectedPoolMinionMultiplier: {
    label: "MINION Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected MINION pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolSoldierMultiplier: {
    label: "SOLDIER Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected SOLDIER pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolEliteMultiplier: {
    label: "ELITE Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected ELITE pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolBossMultiplier: {
    label: "BOSS Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected BOSS pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  poolWeakerSideWeight: {
    label: "Lower Pool Side Weight",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make the weaker pool matter more in survivability scoring.",
    affects: "baseline",
    format: "share",
    aliases: ["weaker side", "health pool", "survivability"],
  },
  poolAverageWeight: {
    label: "Average Pool Weight",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make the average of both pools matter more.",
    affects: "baseline",
    format: "share",
    aliases: ["average", "health pool", "survivability"],
  },
  poolBelowExpectedMaxPenaltyShare: {
    label: "Below-Expected Pool Penalty Cap",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to punish low pools more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["penalty", "health pool", "survivability"],
  },
  poolBelowExpectedScale: {
    label: "Below-Expected Pool Penalty Speed",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make low-pool penalties ramp more slowly.",
    affects: "baseline",
    format: "share",
    aliases: ["penalty", "health pool", "scale"],
  },
  poolAboveExpectedMaxBonusShare: {
    label: "Above-Expected Pool Bonus Cap",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to reward high pools more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["bonus", "health pool", "survivability"],
  },
  poolAboveExpectedScale: {
    label: "Above-Expected Pool Bonus Speed",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make high-pool bonuses ramp more slowly.",
    affects: "baseline",
    format: "share",
    aliases: ["bonus", "health pool", "scale"],
  },
  defenceStringProtectionOutputMaxShare: {
    label: "Protection Block Survivability Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to let protection block contribute more survivability axis.",
    affects: "baseline",
    format: "share",
    aliases: ["defence package", "block", "survivability"],
  },
  defenceStringProtectionOutputScale: {
    label: "Protection Block Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make protection block survivability ramp more slowly.",
    affects: "baseline",
    aliases: ["defence package", "block", "scale"],
  },
  dodgeBaselineMaxShare: {
    label: "Dodge Baseline Survivability Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to let any Dodge dice add more survivability.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "defence package", "survivability"],
  },
  dodgeBaselineScale: {
    label: "Dodge Baseline Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make baseline Dodge value ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "defence package", "scale"],
  },
  dodgeParityMaxShare: {
    label: "Dodge Parity Survivability Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward matching expected incoming attack dice more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "parity", "expected incoming"],
  },
  dodgeParityScale: {
    label: "Dodge Parity Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make parity rewards ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "parity", "scale"],
  },
  dodgeAboveExpectedMaxShare: {
    label: "Above-Expected Dodge Bonus Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward one extra Dodge die more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "above expected", "bonus"],
  },
  dodgeAboveExpectedScale: {
    label: "Above-Expected Dodge Bonus Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make the extra-Dodge bonus ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "above expected", "scale"],
  },
  dodgeExtremeAboveExpectedMaxShare: {
    label: "Extreme Dodge Bonus Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward very high Dodge dice more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "extreme", "bonus"],
  },
  dodgeExtremeAboveExpectedScale: {
    label: "Extreme Dodge Bonus Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make very high Dodge bonuses ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "extreme", "scale"],
  },
  dodgeTotalMaxShare: {
    label: "Total Dodge Survivability Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to allow Dodge to contribute more total survivability.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "cap", "survivability"],
  },
};

export const COMBAT_TUNING_ADMIN_METADATA: Record<string, CombatTuningAdminMetadata> =
  Object.fromEntries(
    COMBAT_TUNING_CONFIG_KEY_ORDER.map((key) => [
      key,
      METADATA[key] ?? {
        label: key,
        group: "Misc Combat Baseline",
        description: "Combat baseline tuning value.",
        affects: "baseline",
      },
    ]),
  );
