import { COMBAT_TUNING_CONFIG_KEY_ORDER } from "@/lib/config/combatTuningShared";

export const COMBAT_TUNING_ADMIN_GROUPS = [
  "Protection Formula",
  "Baseline Resilience & Perseverance",
  "Pool Expectation by Tier",
  "Pool Penalty / Bonus Scaling",
  "Raw Axis Budget Targets",
  "Attribute Weights / Realization Inputs",
  "Dodge & Defence Package",
  "Misc Combat Baseline",
] as const;

export type CombatTuningAdminGroup = (typeof COMBAT_TUNING_ADMIN_GROUPS)[number];
export type CombatTuningValueFormat = "number" | "multiplier" | "share";

export type CombatTuningAdminMetadata = {
  label: string;
  group: CombatTuningAdminGroup;
  description: string;
  affects: "baseline";
  format?: CombatTuningValueFormat;
  suggestedMin?: number;
  suggestedMax?: number;
  aliases?: string[];
};

const METADATA: Record<string, CombatTuningAdminMetadata> = {
  protectionK: {
    label: "Protection Output Divider",
    group: "Protection Formula",
    description: "Raise this to make protection block fewer wounds per success.",
    affects: "baseline",
    suggestedMin: 1,
    suggestedMax: 12,
    aliases: ["K", "block", "protection"],
  },
  protectionS: {
    label: "Protection Skill Scaling Divider",
    group: "Protection Formula",
    description: "Raise this to make Armor Skill and Willpower add less block value.",
    affects: "baseline",
    suggestedMin: 1,
    suggestedMax: 12,
    aliases: ["S", "skill", "block", "protection"],
  },
  attackWeight: {
    label: "Attack Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Attack add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  guardWeight: {
    label: "Guard Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Guard add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  fortitudeWeight: {
    label: "Fortitude Weight for Physical Resilience",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Fortitude add more physical resilience.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["physical resilience", "attributes"],
  },
  intellectWeight: {
    label: "Intellect Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Intellect add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  synergyWeight: {
    label: "Synergy Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Synergy add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  braveryWeight: {
    label: "Bravery Weight for Mental Perseverance",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Bravery add more mental perseverance.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["mental perseverance", "attributes"],
  },
  weaponSkillBraveryWeight: {
    label: "Bravery Weight for Weapon Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Bravery matter more for Weapon Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill"],
  },
  weaponSkillAttackWeight: {
    label: "Attack Weight for Weapon Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Attack matter more for Weapon Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill"],
  },
  weaponSkillBaselineOffset: {
    label: "Weapon Skill Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Weapon Skill overall.",
    affects: "baseline",
    aliases: ["weapon skill", "attack skill", "offset"],
  },
  weaponSkillScale: {
    label: "Weapon Skill Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Weapon Skill faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["weapon skill", "attack skill", "curve"],
  },
  armorSkillFortitudeWeight: {
    label: "Fortitude Weight for Armor Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Fortitude matter more for Armor Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill"],
  },
  armorSkillGuardWeight: {
    label: "Guard Weight for Armor Skill",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Guard matter more for Armor Skill.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill"],
  },
  armorSkillBaselineOffset: {
    label: "Armor Skill Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Armor Skill overall.",
    affects: "baseline",
    aliases: ["armor skill", "defence skill", "offset"],
  },
  armorSkillScale: {
    label: "Armor Skill Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Armor Skill faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["armor skill", "defence skill", "curve"],
  },
  willpowerSynergyWeight: {
    label: "Synergy Weight for Willpower Pool",
    group: "Attribute Weights / Realization Inputs",
    description:
      "Raise this to make Synergy matter more for the pooled Willpower value that supports mental protection.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental protection"],
  },
  willpowerBraveryWeight: {
    label: "Bravery Weight for Willpower Pool",
    group: "Attribute Weights / Realization Inputs",
    description:
      "Raise this to make Bravery matter more for the pooled Willpower value while Bravery remains the surfaced Mental Defence stat.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental protection"],
  },
  willpowerBaselineOffset: {
    label: "Willpower Baseline Offset",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower Willpower overall.",
    affects: "baseline",
    aliases: ["willpower", "mental defence", "offset"],
  },
  willpowerScale: {
    label: "Willpower Scale",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make better attributes increase Willpower faster.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["willpower", "mental defence", "curve"],
  },
  dodgeIntellectWeight: {
    label: "Intellect Weight for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Intellect increase Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "attribute"],
  },
  dodgeGuardWeight: {
    label: "Guard Weight for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Guard increase Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "attribute"],
  },
  dodgeAttributeDivisor: {
    label: "Dodge Attribute Divisor",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to lower the attribute part of Dodge overall.",
    affects: "baseline",
    aliases: ["dodge", "avoidance", "divider", "divisor"],
  },
  dodgeProtectionPenaltyWeight: {
    label: "Protection Penalty for Dodge",
    group: "Attribute Weights / Realization Inputs",
    description: "Raise this to make Physical Protection reduce Dodge more.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["dodge", "avoidance", "protection", "penalty"],
  },
  minionTierMultiplier: {
    label: "MINION Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give MINION monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  soldierTierMultiplier: {
    label: "SOLDIER Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give SOLDIER monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  eliteTierMultiplier: {
    label: "ELITE Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give ELITE monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  bossTierMultiplier: {
    label: "BOSS Resilience Multiplier",
    group: "Baseline Resilience & Perseverance",
    description: "Raise this to give BOSS monsters larger resilience and perseverance pools.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["tier", "pool", "resilience", "perseverance"],
  },
  expectedPhysicalResilienceAt1: {
    label: "Expected Physical Resilience at Level 1",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the calculator expect a tougher physical pool at level 1.",
    affects: "baseline",
    aliases: ["health pool", "physical resilience", "expected"],
  },
  expectedPhysicalResiliencePerLevel: {
    label: "Expected Physical Resilience per Level",
    group: "Pool Expectation by Tier",
    description: "Raise this to make expected physical resilience grow faster by level.",
    affects: "baseline",
    aliases: ["health pool", "physical resilience", "expected"],
  },
  expectedMentalPerseveranceAt1: {
    label: "Expected Mental Perseverance at Level 1",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the calculator expect a tougher mental pool at level 1.",
    affects: "baseline",
    aliases: ["health pool", "mental perseverance", "expected"],
  },
  expectedMentalPerseverancePerLevel: {
    label: "Expected Mental Perseverance per Level",
    group: "Pool Expectation by Tier",
    description: "Raise this to make expected mental perseverance grow faster by level.",
    affects: "baseline",
    aliases: ["health pool", "mental perseverance", "expected"],
  },
  expectedPoolMinionMultiplier: {
    label: "MINION Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected MINION pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolSoldierMultiplier: {
    label: "SOLDIER Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected SOLDIER pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolEliteMultiplier: {
    label: "ELITE Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected ELITE pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  expectedPoolBossMultiplier: {
    label: "BOSS Expected Pool Multiplier",
    group: "Pool Expectation by Tier",
    description: "Raise this to make the expected BOSS pool baseline higher.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["health pool", "expected", "tier"],
  },
  poolWeakerSideWeight: {
    label: "Legacy Lower Pool Side Weight",
    group: "Pool Penalty / Bonus Scaling",
    description: "Legacy combined-pool control from the old single survivability axis.",
    affects: "baseline",
    format: "share",
    aliases: ["legacy", "weaker side", "health pool", "survivability"],
  },
  poolAverageWeight: {
    label: "Legacy Average Pool Weight",
    group: "Pool Penalty / Bonus Scaling",
    description: "Legacy combined-pool control from the old single survivability axis.",
    affects: "baseline",
    format: "share",
    aliases: ["legacy", "average", "health pool", "survivability"],
  },
  poolAtExpectedShare: {
    label: "Expected Pool Lane Share",
    group: "Pool Penalty / Bonus Scaling",
    description:
      "When a physical or mental pool is exactly on its expected baseline, this is the share of that lane budget it contributes before protection and dodge are added.",
    affects: "baseline",
    format: "share",
    suggestedMin: 0,
    suggestedMax: 1,
    aliases: ["parity", "expected", "health pool", "survivability"],
  },
  poolBelowExpectedMaxPenaltyShare: {
    label: "Below-Expected Pool Penalty Cap",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to punish low pools more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["penalty", "health pool", "survivability"],
  },
  poolBelowExpectedScale: {
    label: "Below-Expected Pool Penalty Speed",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make low-pool penalties ramp more slowly.",
    affects: "baseline",
    format: "share",
    aliases: ["penalty", "health pool", "scale"],
  },
  poolAboveExpectedMaxBonusShare: {
    label: "Above-Expected Pool Bonus Cap",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to reward high pools more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["bonus", "health pool", "survivability"],
  },
  poolAboveExpectedScale: {
    label: "Above-Expected Pool Bonus Speed",
    group: "Pool Penalty / Bonus Scaling",
    description: "Raise this to make high-pool bonuses ramp more slowly.",
    affects: "baseline",
    format: "share",
    aliases: ["bonus", "health pool", "scale"],
  },
  atWillThreatAxisMultiplier: {
    label: "At-Will Threat Axis Multiplier",
    group: "Raw Axis Budget Targets",
    description:
      "Multiplies natural and equipped at-will attack contribution on threat axes without changing the presence pressure budget.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["at-will", "weapon", "natural attack", "threat", "axis budget"],
  },
  defenceStringProtectionOutputMaxShare: {
    label: "Protection Block Lane Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to let protection block contribute more physical or mental survivability.",
    affects: "baseline",
    format: "share",
    aliases: ["defence package", "block", "survivability"],
  },
  defenceStringProtectionOutputScale: {
    label: "Protection Block Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make protection block contribution ramp more slowly in each survivability lane.",
    affects: "baseline",
    aliases: ["defence package", "block", "scale"],
  },
  mentalDefenceStringProtectionOutputMaxShare: {
    label: "Mental Protection Block Lane Cap",
    group: "Dodge & Defence Package",
    description:
      "Raise this to let mental protection contribute more mental survivability without changing physical protection output.",
    affects: "baseline",
    format: "share",
    aliases: ["mental defence", "mpv", "block", "survivability"],
  },
  mentalDefenceStringProtectionOutputScale: {
    label: "Mental Protection Block Ramp Speed",
    group: "Dodge & Defence Package",
    description:
      "Raise this to make mental protection contribution ramp more slowly without changing physical protection ramping.",
    affects: "baseline",
    aliases: ["mental defence", "mpv", "block", "scale"],
  },
  dodgeBaselineMaxShare: {
    label: "Dodge Baseline Lane Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to let any Dodge dice add more physical survivability.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "defence package", "survivability"],
  },
  dodgeBaselineScale: {
    label: "Dodge Baseline Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make baseline Dodge value ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "defence package", "scale"],
  },
  dodgeParityMaxShare: {
    label: "Dodge Parity Lane Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward matching expected incoming attack dice more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "parity", "expected incoming"],
  },
  dodgeParityScale: {
    label: "Dodge Parity Ramp Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make parity rewards ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "parity", "scale"],
  },
  dodgeAboveExpectedMaxShare: {
    label: "Above-Expected Dodge Bonus Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward one extra Dodge die more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "above expected", "bonus"],
  },
  dodgeAboveExpectedScale: {
    label: "Above-Expected Dodge Bonus Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make the extra-Dodge bonus ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "above expected", "scale"],
  },
  dodgeExtremeAboveExpectedMaxShare: {
    label: "Extreme Dodge Bonus Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to reward very high Dodge dice more strongly.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "extreme", "bonus"],
  },
  dodgeExtremeAboveExpectedScale: {
    label: "Extreme Dodge Bonus Speed",
    group: "Dodge & Defence Package",
    description: "Raise this to make very high Dodge bonuses ramp more slowly.",
    affects: "baseline",
    aliases: ["dodge", "extreme", "scale"],
  },
  dodgeTotalMaxShare: {
    label: "Total Dodge Physical Survivability Cap",
    group: "Dodge & Defence Package",
    description: "Raise this to allow Dodge to contribute more total physical survivability.",
    affects: "baseline",
    format: "share",
    aliases: ["dodge", "cap", "survivability"],
  },
  rawPhysicalSurvivabilityBudgetAt1: {
    label: "Raw Physical Survivability Budget at Level 1",
    group: "Raw Axis Budget Targets",
    description:
      "Raw physical survivability lane budget before display normalization. Outcome Normalization display curves should not change this.",
    affects: "baseline",
    aliases: ["raw budget", "physical survivability", "axis budget"],
  },
  rawPhysicalSurvivabilityBudgetPerLevel: {
    label: "Raw Physical Survivability Budget per Level",
    group: "Raw Axis Budget Targets",
    description: "Per-level growth for the raw physical survivability lane budget.",
    affects: "baseline",
    aliases: ["raw budget", "physical survivability", "axis budget"],
  },
  rawMentalSurvivabilityBudgetAt1: {
    label: "Raw Mental Survivability Budget at Level 1",
    group: "Raw Axis Budget Targets",
    description:
      "Raw mental survivability lane budget before display normalization. Outcome Normalization display curves should not change this.",
    affects: "baseline",
    aliases: ["raw budget", "mental survivability", "axis budget"],
  },
  rawMentalSurvivabilityBudgetPerLevel: {
    label: "Raw Mental Survivability Budget per Level",
    group: "Raw Axis Budget Targets",
    description: "Per-level growth for the raw mental survivability lane budget.",
    affects: "baseline",
    aliases: ["raw budget", "mental survivability", "axis budget"],
  },
  rawSurvivabilityBudgetMinionMultiplier: {
    label: "MINION Raw Survivability Budget Multiplier",
    group: "Raw Axis Budget Targets",
    description: "Tier multiplier for raw survivability lane budgets.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["raw budget", "tier", "survivability"],
  },
  rawSurvivabilityBudgetSoldierMultiplier: {
    label: "SOLDIER Raw Survivability Budget Multiplier",
    group: "Raw Axis Budget Targets",
    description: "Tier multiplier for raw survivability lane budgets.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["raw budget", "tier", "survivability"],
  },
  rawSurvivabilityBudgetEliteMultiplier: {
    label: "ELITE Raw Survivability Budget Multiplier",
    group: "Raw Axis Budget Targets",
    description: "Tier multiplier for raw survivability lane budgets.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["raw budget", "tier", "survivability"],
  },
  rawSurvivabilityBudgetBossMultiplier: {
    label: "BOSS Raw Survivability Budget Multiplier",
    group: "Raw Axis Budget Targets",
    description: "Tier multiplier for raw survivability lane budgets.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["raw budget", "tier", "survivability"],
  },
  rawSurvivabilityBudgetLegendaryMultiplier: {
    label: "LEGENDARY Raw Survivability Budget Multiplier",
    group: "Raw Axis Budget Targets",
    description: "Tier multiplier for raw survivability lane budgets.",
    affects: "baseline",
    format: "multiplier",
    aliases: ["raw budget", "tier", "survivability"],
  },
};

export const COMBAT_TUNING_ADMIN_METADATA: Record<string, CombatTuningAdminMetadata> =
  Object.fromEntries(
    COMBAT_TUNING_CONFIG_KEY_ORDER.map((key) => [
      key,
      METADATA[key] ?? {
        label: key,
        group: "Misc Combat Baseline",
        description: "Combat baseline tuning value.",
        affects: "baseline",
      },
    ]),
  );

