import type {
  BaselinePolicy,
  BenchmarkFamily,
  MutationSafetyDeclaration,
  RunnableSuiteDefinition,
  RunnerMode,
  SuiteDefinition,
} from "./balanceBenchmark.schema";
import { dirname, resolve } from "node:path";

const nodeCommand = process.execPath;
const npxCliPath = resolve(dirname(process.execPath), "node_modules/npm/bin/npx-cli.js");

const syntheticReadOnly: MutationSafetyDeclaration = {
  classification: "READ_ONLY",
  declaredReadOnly: true,
  databaseAccess: "none",
  databaseWrites: false,
  assetWrites: false,
  tuningWrites: false,
  baselineWrites: false,
  repositoryWrites: false,
  rationale: "Verified synthetic/self-asserting command with no Prisma client or file-write path.",
};

const databaseReadOnly: MutationSafetyDeclaration = {
  classification: "READ_ONLY",
  declaredReadOnly: true,
  databaseAccess: "read-only",
  databaseWrites: false,
  assetWrites: false,
  tuningWrites: false,
  baselineWrites: false,
  repositoryWrites: false,
  rationale: "Static inspection found only read queries; the runner also compares repository status before and after execution.",
};

const guardedReconciliationDryRunReadOnly: MutationSafetyDeclaration = {
  classification: "READ_ONLY",
  declaredReadOnly: true,
  databaseAccess: "read-only",
  databaseWrites: false,
  assetWrites: false,
  tuningWrites: false,
  baselineWrites: false,
  repositoryWrites: false,
  rationale: "The CLI contains separately guarded apply capability, but this fixed registry command omits --apply and therefore executes only the read-only plan path.",
};

const selfAsserting = (notes: string): BaselinePolicy => ({
  kind: "SELF_ASSERTING",
  acceptedReference: "Assertions embedded in the committed smoke script.",
  extraction: "EXIT_CODE",
  notes,
});

const structuredCommand = (notes: string): BaselinePolicy => ({
  kind: "STRUCTURED_OUTPUT",
  acceptedReference: null,
  extraction: "STABLE_JSON",
  notes,
});

const commandOnly = (notes: string): BaselinePolicy => ({
  kind: "COMMAND_ONLY",
  acceptedReference: null,
  extraction: "UNAVAILABLE",
  notes,
});

type SuiteInput = Omit<RunnableSuiteDefinition, "command" | "arguments"> & {
  script: string;
  arguments?: string[];
};

function tsxSuite(input: SuiteInput): SuiteDefinition {
  return {
    ...input,
    command: nodeCommand,
    arguments: [npxCliPath, "--yes", "tsx", input.script, ...(input.arguments ?? [])],
  };
}

const prismaDependencyPatterns = ["prisma/schema.prisma", "prisma/client.ts"];
const tuningDependencyPatterns = [
  "lib/config/powerTuning*.ts",
  "lib/config/combatTuning*.ts",
  "lib/config/outcomeNormalization*.ts",
];
const outcomeDependencyPatterns = [
  "lib/calculators/monsterOutcomeCalculator.ts",
  "lib/calculators/calculatorConfig.ts",
  "lib/summoning/types.ts",
  "lib/summoning/resolvePowerCooldownAuthority.ts",
  ...tuningDependencyPatterns,
];
const powerDependencyPatterns = [
  "lib/summoning/powerCostResolver.ts",
  "lib/summoning/types.ts",
  "lib/config/powerTuning*.ts",
];
const cooldownCacheSynchronizationDependencyPatterns = [
  "lib/summoning/powerCooldownCacheSynchronization.ts",
  "app/api/summoning-circle/monsters/route.ts",
  "app/api/summoning-circle/monsters/[id]/route.ts",
  "app/api/summoning-circle/monsters/[id]/copy/route.ts",
  "lib/characterBuilder/powers.ts",
  "app/api/campaigns/[id]/characters/[characterId]/builder/route.ts",
];
const characterCooldownCacheDependencyPatterns = [
  "lib/summoning/powerCooldownCacheSynchronization.ts",
  "lib/characterBuilder/powers.ts",
  "app/api/campaigns/[id]/characters/[characterId]/builder/route.ts",
];
const monsterCooldownCacheReconciliationDependencyPatterns = [
  "scripts/powerCooldownCacheReconciliation.shared.ts",
  "scripts/powerCooldownCacheReconciliation.apply.ts",
  "scripts/powerCooldownCacheReconciliation.smoke.ts",
  "scripts/reconcileMonsterPowerCooldownCaches.ts",
  "lib/summoning/powerCooldownCacheSynchronization.ts",
  "lib/summoning/resolvePowerCooldownAuthority.ts",
  "app/api/summoning-circle/monsters/route.ts",
  "app/api/summoning-circle/monsters/[id]/route.ts",
  "app/api/summoning-circle/monsters/[id]/copy/route.ts",
  "lib/config/powerTuning*.ts",
  ...prismaDependencyPatterns,
];
const characterCooldownCacheReconciliationDependencyPatterns = [
  "scripts/powerCooldownCacheReconciliation.shared.ts",
  "scripts/powerCooldownCacheReconciliation.apply.ts",
  "scripts/powerCooldownCacheReconciliation.smoke.ts",
  "scripts/reconcileCharacterPowerCooldownCaches.ts",
  "lib/summoning/powerCooldownCacheSynchronization.ts",
  "lib/summoning/resolvePowerCooldownAuthority.ts",
  "lib/characterBuilder/powers.ts",
  "lib/characterBuilder/core.ts",
  "app/api/campaigns/[id]/characters/[characterId]/builder/route.ts",
  "lib/config/powerTuning*.ts",
  "lib/config/characterBuilderTuning*.ts",
  ...prismaDependencyPatterns,
];
const combatLabDependencyPatterns = [
  "lib/combat-lab/**",
  "lib/summoning/types.ts",
  "lib/summoning/resolvePowerCooldownAuthority.ts",
  ...tuningDependencyPatterns,
  ...prismaDependencyPatterns,
];
const augmentDebuffThreeFieldSemanticDependencyPatterns = [
  "prisma/schema.prisma",
  "prisma/migrations/*_add_effect_packet_modifier/migration.sql",
  "lib/summoning/types.ts",
  "lib/summoning/powerCostResolver.ts",
  "lib/summoning/validation.ts",
  "lib/powers/authoringRules.ts",
  "app/api/summoning-circle/monsters/route.ts",
  "app/api/summoning-circle/monsters/[id]/route.ts",
  "app/api/summoning-circle/monsters/[id]/copy/route.ts",
  "lib/characterBuilder/powers.ts",
  "app/api/campaigns/[id]/characters/[characterId]/builder/route.ts",
  "lib/combat-lab/types.ts",
  "lib/combat-lab/powerAdapter.ts",
  "lib/combat-lab/actionResolver.ts",
  "lib/combat-lab/combatState.ts",
  "lib/combat-lab/liveAdapters.ts",
  "scripts/augmentDebuffThreeFieldSemantic.smoke.ts",
];
const summoningCircleModifierInfrastructureDependencyPatterns = [
  "app/summoning-circle/components/SummoningCircleEditor.tsx",
  "lib/summoning/monsterPowerReconciliation.ts",
  "lib/summoning/validation.ts",
  "lib/summoning/powerCostResolver.ts",
  "lib/powers/authoringRules.ts",
  "app/api/summoning-circle/monsters/route.ts",
  "app/api/summoning-circle/monsters/[id]/route.ts",
  "scripts/summoningCircleModifierInfrastructure.smoke.ts",
];
const augmentDebuffEconomicsDependencyPatterns = [
  "lib/summoning/augmentDebuffEconomics.ts",
  "lib/summoning/powerCostResolver.ts",
  "lib/config/powerTuningShared.ts",
  "lib/config/powerTuningAdminMetadata.ts",
  "scripts/augmentDebuffEconomics.smoke.ts",
];

export const BALANCE_BENCHMARK_REGISTRY: readonly SuiteDefinition[] = [
  {
    id: "project-typecheck",
    title: "Project TypeScript compilation",
    family: "Core resolver and cooldown authority",
    description: "Compile the complete project without emitting files.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    command: nodeCommand,
    arguments: ["node_modules/typescript/bin/tsc", "--noEmit"],
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: [
      "scripts/balanceBenchmark.*.ts",
      "tsconfig.json",
      "next-env.d.ts",
      "package.json",
      ...cooldownCacheSynchronizationDependencyPatterns,
    ],
    failureSeverity: "BLOCKER",
    supportsJson: false,
    baselinePolicy: commandOnly("Compiler diagnostics are infrastructure failures, not balance baselines."),
    notes: ["Uses the repository TypeScript configuration and emits no files."],
  },
  tsxSuite({
    id: "power-cost-resolver-smoke",
    title: "Power-cost resolver smoke",
    family: "Core resolver and cooldown authority",
    description: "Run the committed power pricing and resolver assertions.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/powerCostResolver.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: [
      "scripts/powerCostResolver.smoke.ts",
      ...powerDependencyPatterns,
      ...cooldownCacheSynchronizationDependencyPatterns,
    ],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("A non-zero assertion exit is a balance regression."),
    notes: ["The script prints diagnostics but does not expose a JSON-only CLI contract."],
  }),
  tsxSuite({
    id: "power-cooldown-authority-smoke",
    title: "Power cooldown-authority smoke",
    family: "Core resolver and cooldown authority",
    description: "Verify active-tuning cooldown authority across current consumers.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/powerCooldownAuthority.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: [
      "scripts/powerCooldownAuthority.smoke.ts",
      "lib/summoning/resolvePowerCooldownAuthority.ts",
      "lib/combat-lab/powerAdapter.ts",
      "lib/summoning/render.ts",
      ...powerDependencyPatterns,
      ...outcomeDependencyPatterns,
      ...cooldownCacheSynchronizationDependencyPatterns,
    ],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("A non-zero assertion exit is an authority regression."),
    notes: [],
  }),
  tsxSuite({
    id: "power-cooldown-cache-synchronization-smoke",
    title: "Power cooldown-cache synchronization smoke",
    family: "Core resolver and cooldown authority",
    description: "Verify pure save-time cooldown-cache synchronization and batch failure behavior.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/powerCooldownCacheSynchronization.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: [
      "scripts/powerCooldownCacheSynchronization.smoke.ts",
      ...cooldownCacheSynchronizationDependencyPatterns,
      ...powerDependencyPatterns,
    ],
    failureSeverity: "BLOCKER",
    supportsJson: false,
    baselinePolicy: selfAsserting("A non-zero assertion exit is a save-time cache synchronization blocker."),
    notes: ["Uses in-memory fixtures only and performs no database or repository writes."],
  }),
  tsxSuite({
    id: "power-cooldown-cache-reconciliation-monsters",
    title: "Persisted monster cooldown-cache reconciliation",
    family: "Core resolver and cooldown authority",
    description: "Inventory persisted monster powers against authoritative current-balance cooldown caches.",
    compatibility: "AVAILABLE",
    modes: ["full", "changed"],
    script: "scripts/reconcileMonsterPowerCooldownCaches.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: guardedReconciliationDryRunReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: monsterCooldownCacheReconciliationDependencyPatterns,
    failureSeverity: "BLOCKER",
    supportsJson: true,
    baselinePolicy: structuredCommand("Ordinary persisted-cache mismatches are expected dry-run evidence; unresolved or infrastructure failures block."),
    notes: ["The CLI has separately guarded apply capability, but the benchmark command is permanently dry-run and never supplies --apply."],
  }),
  tsxSuite({
    id: "power-cooldown-cache-reconciliation-characters",
    title: "Persisted Character Builder cooldown-cache reconciliation",
    family: "Core resolver and cooldown authority",
    description: "Inventory ordinary and signature powers against authoritative current-balance cooldown caches.",
    compatibility: "AVAILABLE",
    modes: ["full", "changed"],
    script: "scripts/reconcileCharacterPowerCooldownCaches.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: guardedReconciliationDryRunReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: characterCooldownCacheReconciliationDependencyPatterns,
    failureSeverity: "BLOCKER",
    supportsJson: true,
    baselinePolicy: structuredCommand("Ordinary persisted-cache mismatches are expected dry-run evidence; unresolved or infrastructure failures block."),
    notes: ["The CLI has separately guarded apply capability, but the benchmark command is permanently dry-run and never supplies --apply."],
  }),
  tsxSuite({
    id: "augment-debuff-three-field-semantic-smoke",
    title: "Augment/Debuff three-field semantic smoke",
    family: "Combat Lab runtime",
    description: "Verify the legacy-safe dual-read semantic foundation with fifty in-memory assertions.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/augmentDebuffThreeFieldSemantic.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: augmentDebuffThreeFieldSemanticDependencyPatterns,
    failureSeverity: "BLOCKER",
    supportsJson: false,
    baselinePolicy: selfAsserting("The focused smoke owns the locked three-field semantic contract."),
    notes: ["Uses in-memory fixtures only; public Modifier authoring remains disabled."],
  }),
  tsxSuite({
    id: "summoning-circle-modifier-infrastructure-smoke",
    title: "Summoning Circle Modifier infrastructure smoke",
    family: "Core resolver and cooldown authority",
    description: "Verify stable client identity, API normalization/reconciliation, and fail-closed semantic preview infrastructure.",
    compatibility: "AVAILABLE",
    modes: ["full", "changed"],
    script: "scripts/summoningCircleModifierInfrastructure.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: summoningCircleModifierInfrastructureDependencyPatterns,
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("The focused smoke owns Summoning identity, reconciliation, and preview preflight invariants."),
    notes: ["Uses deterministic in-memory fixtures and static source assertions; performs no database or repository writes."],
  }),
  tsxSuite({
    id: "augment-debuff-economics-smoke",
    title: "Augment/Debuff economic primitives smoke",
    family: "Core resolver and cooldown authority",
    description:
      "Verify exact delivery-unit primitives and the approved code-owned BPV conversion.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/augmentDebuffEconomics.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: augmentDebuffEconomicsDependencyPatterns,
    failureSeverity: "BLOCKER",
    supportsJson: false,
    baselinePolicy: selfAsserting(
      "The focused smoke owns the calibrated Phase 2B delivery-unit contract.",
    ),
    notes: [
      "Uses deterministic in-memory enumeration only; no database access or authoring activation.",
    ],
  }),
  tsxSuite({
    id: "combat-lab-smoke",
    title: "Combat Lab smoke",
    family: "Combat Lab runtime",
    description: "Run deterministic synthetic Combat Lab runtime assertions.",
    compatibility: "AVAILABLE",
    modes: ["runtime", "full", "changed"],
    script: "scripts/combatLab.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/combatLab.smoke.ts", ...combatLabDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("The script owns deterministic runtime invariants."),
    notes: [],
  }),
  tsxSuite({
    id: "combat-lab-party-boss-context",
    title: "Combat Lab party/Boss context",
    family: "Combat Lab runtime",
    description: "Run the read-only party/Boss reference scenarios.",
    compatibility: "AVAILABLE",
    modes: ["runtime", "full", "changed"],
    script: "scripts/combatLab.partyBossContextRead.ts",
    arguments: ["--runs", "100", "--seed", "4242", "--json"],
    deterministicSeeds: [4242],
    mutationSafety: databaseReadOnly,
    timeoutMs: 300_000,
    changedPathPatterns: ["scripts/combatLab.partyBossContextRead.ts", ...combatLabDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: true,
    baselinePolicy: structuredCommand("Stable JSON is captured; no new baseline is inferred."),
    notes: ["Uses the script's committed default run count and deterministic seed."],
  }),
  tsxSuite({
    id: "combat-lab-legendary-elite-matrix",
    title: "Combat Lab legendary/elite benchmark matrix",
    family: "Combat Lab runtime",
    description: "Run the read-only legendary/elite benchmark references.",
    compatibility: "AVAILABLE",
    modes: ["runtime", "full", "changed"],
    script: "scripts/combatLab.legendaryEliteBenchmarkMatrix.ts",
    arguments: ["--runs", "100", "--seed", "4242", "--json"],
    deterministicSeeds: [4242],
    mutationSafety: databaseReadOnly,
    timeoutMs: 300_000,
    changedPathPatterns: ["scripts/combatLab.legendaryEliteBenchmarkMatrix.ts", ...combatLabDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: true,
    baselinePolicy: structuredCommand("Stable JSON is captured; tolerances remain registry/contract governed."),
    notes: ["Uses the script's committed default run count and deterministic seed."],
  }),
  tsxSuite({
    id: "combat-lab-scenario-matrix",
    title: "Combat Lab scenario matrix",
    family: "Combat Lab runtime",
    description: "Run the official Balance Environment core preset deterministically.",
    compatibility: "AVAILABLE",
    modes: ["runtime", "full", "changed"],
    script: "scripts/combatLab.scenarioMatrix.ts",
    arguments: [
      "--preset",
      "balance-environment-core",
      "--runs",
      "100",
      "--seed",
      "4242",
      "--balance-environment",
      "--json",
    ],
    deterministicSeeds: [4242],
    mutationSafety: databaseReadOnly,
    timeoutMs: 600_000,
    changedPathPatterns: ["scripts/combatLab.scenarioMatrix.ts", ...combatLabDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: true,
    baselinePolicy: structuredCommand("Stable JSON is captured; no --out path is supplied."),
    notes: ["The registry deliberately omits --out so the suite cannot create a report file."],
  }),
  tsxSuite({
    id: "character-power-builder-smoke",
    title: "Character Builder power smoke",
    family: "Character Builder powers",
    description: "Run Character Builder power budget and authority assertions.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/characterPowerBuilder.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: [
      "scripts/characterPowerBuilder.smoke.ts",
      "lib/characterBuilder/**",
      "lib/powers/**",
      ...characterCooldownCacheDependencyPatterns,
      ...powerDependencyPatterns,
    ],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("A non-zero assertion exit is a builder regression."),
    notes: [],
  }),
  tsxSuite({
    id: "outcome-calculator-smoke",
    title: "Outcome Calculator smoke",
    family: "Outcome Calculator smoke",
    description: "Run accepted calculator invariant and axis-anchor assertions.",
    compatibility: "AVAILABLE",
    modes: ["quick", "full", "changed"],
    script: "scripts/monsterOutcomeCalculator.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/monsterOutcomeCalculator.smoke.ts", ...outcomeDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("A non-zero assertion exit is a calculator regression."),
    notes: [],
  }),
  tsxSuite({
    id: "power-threat-monotonic-smoke",
    title: "Power Threat monotonic smoke",
    family: "Threat reconciliation",
    description: "Verify monotonic Threat behavior using synthetic powers.",
    compatibility: "AVAILABLE",
    modes: ["axes", "full", "changed"],
    script: "scripts/powerThreatMonotonic.smoke.ts",
    deterministicSeeds: [],
    mutationSafety: syntheticReadOnly,
    timeoutMs: 120_000,
    changedPathPatterns: ["scripts/powerThreatMonotonic.smoke.ts", ...powerDependencyPatterns, ...outcomeDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: false,
    baselinePolicy: selfAsserting("This is a monotonic invariant, not a complete Threat reconciliation."),
    notes: ["Does not replace the PARTIAL DB-backed Threat audit."],
  }),
  tsxSuite({
    id: "threat-axis-reconciliation",
    title: "Threat axis reconciliation",
    family: "Threat reconciliation",
    description: "Inspect current authored Threat samples from the Balance Environment.",
    compatibility: "PARTIAL",
    modes: ["axes", "full", "changed"],
    script: "scripts/balanceAudit.summoningCircleAxisReconciliation.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: databaseReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/balanceAudit.summoningCircleAxisReconciliation.ts", ...outcomeDependencyPatterns, ...powerDependencyPatterns, ...prismaDependencyPatterns],
    failureSeverity: "WARNING",
    supportsJson: true,
    baselinePolicy: structuredCommand("Output is inventory evidence only until cooldown authority is attached."),
    notes: ["Predates centralized cooldown authority and invokes built-in power defaults."],
  }),
  tsxSuite({
    id: "durability-axis-reconciliation",
    title: "Durability axis reconciliation",
    family: "Durability reconciliation",
    description: "Inspect authored durability samples and calculator components.",
    compatibility: "PARTIAL",
    modes: ["axes", "full", "changed"],
    script: "scripts/balanceAudit.summoningCircleDurabilityAxisReconciliation.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: databaseReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/balanceAudit.summoningCircleDurabilityAxisReconciliation.ts", ...outcomeDependencyPatterns, ...powerDependencyPatterns, ...prismaDependencyPatterns],
    failureSeverity: "WARNING",
    supportsJson: true,
    baselinePolicy: structuredCommand("Hard smoke anchors remain authoritative; this audit is partial."),
    notes: ["Power packages do not attach centralized cooldown authority."],
  }),
  tsxSuite({
    id: "pressure-axis-reconciliation",
    title: "Pressure and remaining-axis reconciliation",
    family: "Pressure reconciliation",
    description: "Inspect Pressure and remaining-axis authored samples.",
    compatibility: "PARTIAL",
    modes: ["axes", "full", "changed"],
    script: "scripts/balanceAudit.summoningCircleRemainingAxisReconciliation.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: databaseReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/balanceAudit.summoningCircleRemainingAxisReconciliation.ts", ...outcomeDependencyPatterns, ...powerDependencyPatterns, ...prismaDependencyPatterns],
    failureSeverity: "WARNING",
    supportsJson: true,
    baselinePolicy: structuredCommand("Output is partial evidence and cannot become an accepted pass."),
    notes: ["Includes a Mobility inventory, but lacks centralized authority attachment for power packages."],
  }),
  tsxSuite({
    id: "control-pressure-axis-reconciliation",
    title: "Control Pressure axis reconciliation",
    family: "Control Pressure reconciliation",
    description: "Reconcile authored and synthetic Control Pressure semantics with active cooldown authority.",
    compatibility: "AVAILABLE",
    modes: ["axes", "full", "changed"],
    script: "scripts/balanceAudit.summoningCircleControlPressureReconciliation.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: databaseReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: ["scripts/balanceAudit.summoningCircleControlPressureReconciliation.ts", "scripts/monsterOutcomeCalculator.smoke.ts", ...combatLabDependencyPatterns, ...outcomeDependencyPatterns, ...powerDependencyPatterns, ...prismaDependencyPatterns],
    failureSeverity: "REGRESSION",
    supportsJson: true,
    baselinePolicy: structuredCommand("The command self-validates saved/editor parity, movement-denial classification, matched severity ordering, and active cooldown authority."),
    notes: ["Read-only persisted and synthetic evidence; unresolved cooldown authority or failed acceptance exits nonzero."],
  }),
  ...[
    ["atomic-attack-cost-grid", "Atomic attack cost grid", "scripts/balanceAudit.atomicAttackCostGrid.ts"],
    ["control-debuff-cost-grid", "Control/Debuff atomic cost grid", "scripts/balanceAudit.controlDebuffAtomicCostGrid.ts"],
    ["secondary-rider-cost-grid", "Secondary-rider cost grid", "scripts/balanceAudit.secondaryRiderCostGrid.ts"],
    ["forge-strength-cost-grid", "Forge strength cost grid", "scripts/balanceAudit.forgeStrengthCostGrid.ts"],
    ["forge-budget-curve", "Forge budget curve", "scripts/balanceAudit.forgeBudgetCurve.ts"],
  ].map(([id, title, script]): SuiteDefinition =>
    tsxSuite({
      id,
      title,
      family: "Shared success-scaled effect grids",
      description: "Emit a read-only structured pricing grid from active configuration.",
      compatibility: "AVAILABLE",
      modes: ["full", "changed"],
      script,
      arguments: ["--json"],
      deterministicSeeds: [],
      mutationSafety: databaseReadOnly,
      timeoutMs: 180_000,
      changedPathPatterns: [script, ...powerDependencyPatterns, ...tuningDependencyPatterns, ...prismaDependencyPatterns],
      failureSeverity: "BLOCKER",
      supportsJson: true,
      baselinePolicy: structuredCommand("The grid is captured without inferring or rewriting a baseline."),
      notes: [],
    }),
  ),
  tsxSuite({
    id: "synergy-reconciliation",
    title: "Synergy reconciliation",
    family: "Synergy reconciliation",
    description:
      "Reconcile current legacy/cost-derived Synergy evidence with active cooldown authority and current runtime adaptation.",
    compatibility: "AVAILABLE",
    modes: ["axes", "full", "changed"],
    script: "scripts/balanceAudit.summoningCircleSynergyReconciliation.ts",
    arguments: ["--json"],
    deterministicSeeds: [],
    mutationSafety: databaseReadOnly,
    timeoutMs: 180_000,
    changedPathPatterns: [
      "scripts/balanceAudit.summoningCircleSynergyReconciliation.ts",
      ...combatLabDependencyPatterns,
      ...outcomeDependencyPatterns,
      ...powerDependencyPatterns,
      ...tuningDependencyPatterns,
      ...prismaDependencyPatterns,
    ],
    failureSeverity: "REGRESSION",
    supportsJson: true,
    baselinePolicy: structuredCommand(
      "The command self-validates persisted mapping, saved/editor parity, active cooldown authority, current runtime adaptation, and unsuppressed effective axes.",
    ),
    notes: [
      "Audit compatibility repaired; execution remains database-read-only and non-mutating.",
      "Current values remain legacy/cost-derived evidence, not semantic Synergy calibration authority.",
      "Semantic Synergy recalibration remains blocked on approved Level 3 reference suites.",
    ],
  }),
  {
    id: "mobility-reconciliation",
    title: "Mobility reconciliation",
    family: "Mobility reconciliation",
    description: "No dedicated accepted Mobility benchmark exists.",
    compatibility: "MISSING",
    modes: ["full", "changed"],
    command: null,
    arguments: [],
    deterministicSeeds: [],
    mutationSafety: {
      classification: "UNKNOWN",
      declaredReadOnly: false,
      databaseAccess: "unknown",
      rationale: "There is no command to classify; partial inventory currently lives in the Pressure audit.",
    },
    timeoutMs: 0,
    changedPathPatterns: ["lib/calculators/monsterOutcomeCalculator.ts"],
    failureSeverity: "INFORMATIONAL",
    supportsJson: false,
    baselinePolicy: {
      kind: "NONE",
      acceptedReference: null,
      extraction: "UNAVAILABLE",
      notes: "A future dedicated Mobility suite requires separate authorization.",
    },
    notes: ["Mobility inventory in the remaining-axis audit is PARTIAL and not a standalone suite."],
  },
] as const;

export function getSuiteById(id: string): SuiteDefinition | undefined {
  return BALANCE_BENCHMARK_REGISTRY.find((suite) => suite.id === id);
}

export function suitesForMode(mode: RunnerMode): SuiteDefinition[] {
  return BALANCE_BENCHMARK_REGISTRY.filter((suite) => suite.modes.includes(mode));
}

export function registryFamilies(): BenchmarkFamily[] {
  return Array.from(new Set(BALANCE_BENCHMARK_REGISTRY.map((suite) => suite.family)));
}
